language:
    csharp
mono: latest 
dotnet: 3.0

os:
  - linux

before_script:
    - dotnet restore Dramarr.Scrapers/Dramarr.Scrapers.csproj
    - dotnet restore Dramarr.Scrapers.Tests/Dramarr.Scrapers.Tests.csproj
    
script:
    - dotnet build Dramarr.Scrapers/Dramarr.Scrapers.csproj
    - dotnet build Dramarr.Scrapers.Tests/Dramarr.Scrapers.Tests.csproj
    - dotnet test Dramarr.Scrapers.Tests/Dramarr.Scrapers.Tests.csproj