language:
    csharp
dist: trusty 
mono: latest 
dotnet: 3.0

os:
  - linux
  - osx

before_script:
    - dotnet restore ./Dramarr.Scrapers.csproj
    
  
script:
    - dotnet build ./Dramarr.Scrapers.csproj