language:
    csharp
sudo: required
mono: none 
dotnet: 3.0

os:
  - linux

env:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=true

before_script:
    - dotnet restore Dramarr.Scrapers/Dramarr.Scrapers.csproj
    - dotnet restore Dramarr.Scrapers.Tests/Dramarr.Scrapers.Tests.csproj
    
script:
    - dotnet build Dramarr.Scrapers/Dramarr.Scrapers.csproj
    - dotnet build Dramarr.Scrapers.Tests/Dramarr.Scrapers.Tests.csproj
    - dotnet test Dramarr.Scrapers.Tests/Dramarr.Scrapers.Tests.csproj